# Generated by Django 3.1 on 2021-05-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
