# Generated by Django 3.1 on 2021-05-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Portal', '0002_auto_20210522_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='Percentage',
            field=models.FloatField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='Tmarks',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
